### ISSUE TITLE
Use Azure Java SDK 0.7.0

### ISSUE THREAD

**Issue by dadoonet** [elasticsearch/elasticsearch-cloud-azure#38]
It sounds like latest Azure Java SDK now has support for Compute instance management: See https://github.com/Azure/azure-sdk-for-java/issues/218#issuecomment-55394867

So we could try to remove our specific HTTP code (with certificate management) and replace it using this dependency:

```xml
<groupId>com.microsoft.azure</groupId>
<artifactId>azure-management-compute</artifactId>
<version>0.7.0</version>
```

Note that the SDK supports different keystore types (`jceks`, `jks`, `pkcs12`), so we can add a new option `keystore_type` (default to `pkcs12`). BTW, we should may be rename `keystore` to `keystore_path`. Or better, we could also follow Microsoft SDK convention. See: https://github.com/Azure/azure-sdk-for-java/wiki/Devbox-setup#configure-system-environment-variable and https://github.com/Azure/azure-sdk-for-java/blob/master/core/src/main/java/com/microsoft/windowsazure/management/configuration/ManagementConfiguration.java#L32

They are using:

* `management.subscription.id`
* `management.keystore.path`
* `management.keystore.password`
* `management.keystore.type`
* `management.cloud.service.name`

So the `elasticsearch.yml` file could become:

```yaml
cloud:
    azure:
        management:
             subscription.id: XXX-XXX-XXX-XXX
             cloud.service.name: es-demo-app
             keystore:
                   path: /path/to/azurekeystore.pkcs12
                   password: WHATEVER
                   type: pkcs12
```

With the SDK we can replace a lot of code with something like this:

```java
Configuration configuration = ManagementConfiguration.configure(new URI(ENDPOINT),
        SUBSCRIPTION_ID, KEYSTORE_PATH, KEYSTORE_PASSWORD, KeyStoreType.pkcs12);

ComputeManagementClient computeManagementClient = ComputeManagementService.create(configuration);
HostedServiceGetDetailedResponse detailed = computeManagementClient.getHostedServicesOperations().getDetailed(SERVICE_NAME);

for (HostedServiceGetDetailedResponse.Deployment deployment : detailed.getDeployments()) {
    String name = deployment.getName();
    System.out.println("name = " + name);
}
```

It's definitely better than using our own code. We can benefit from that:

* insurance that the code is updated when Azure API changes
* other features we are not using today
